In [3]:
from torch.distributions.categorical import Categorical
import torch

In [5]:
cat_obj = Categorical(probs=torch.tensor([0.25, 0.25, 0.5]))

In [6]:
cat_obj

Categorical(probs: torch.Size([3]))

In [8]:
for i in range(10):
    print(cat_obj.sample().item())

2
1
2
0
1
1
2
2
2
0


In [16]:
cat_obj.log_prob(torch.tensor(2))

tensor(-0.6931)

In [2]:
from learning_rl.helpers.networks import mlp
import torch


In [3]:
net = mlp(sizes=[5, 10, 1])

test_tens = torch.zeros(5)
test_tens

tensor([0., 0., 0., 0., 0.])

In [12]:
ans = net(test_tens)
t_2 = torch.tensor([5])
ans, t_2

(tensor([0.1705], grad_fn=<AddBackward0>), tensor([5]))

In [13]:
sub = ans - t_2
sub

tensor([-4.8295], grad_fn=<SubBackward0>)

In [11]:
sub.tolist()

[-4.829467296600342]

In [17]:
random_ep = torch.ones(4)
random_2_ep = torch.rand(8)
random_ep, random_2_ep

(tensor([1., 1., 1., 1.]),
 tensor([0.7157, 0.4911, 0.0528, 0.3182, 0.2449, 0.2115, 0.3887, 0.4968]))

In [18]:
match = random_2_ep[len(random_2_ep) - len(random_ep):]
match

tensor([0.2449, 0.2115, 0.3887, 0.4968])